blog/urls.py
from django.contrib import admin
from django.urls import path, include  # Import include
from django.conf import settings
from django.conf.urls.static import static
from .views import car_list

urlpatterns = [
    path('', car_list, name='car_list'),
    path('bookings/', include('bookings.urls')),  # Include URLs from the bookings app
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookings/urls.py
from django.urls import path
from .views import booking_form
from . import views

urlpatterns = [
    path('', booking_form, name='booking_form'),
    path('booking/confirmation/', views.booking_confirmation, name='booking_confirmation'),
    path('unavailable-dates/<int:car_id>/', views.get_unavailable_dates, name='unavailable_dates'),
]

new_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from bookings import views as booking_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('book/', booking_views.booking_form, name='book_car'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    from django.urls import path

bookings/models.py
from django.db import models
from django.utils import timezone
from blog.models import Car

class Booking(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=20)
    patent_number = models.CharField(max_length=50)
    insurance = models.CharField(max_length=50, default='normal or not')
    period_start = models.DateField()
    period_end = models.DateField()
    payment_status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} {self.surname}'

class BusyDate(models.Model):
    car_id = models.IntegerField()
    start_date = models.DateField(auto_now=False, auto_now_add=False)
    end_date = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return f"Car ID: {self.car_id}, Start Date: {self.start_date}, End Date: {self.end_date}"

bookings/forms.py
from django import forms
from django.forms.widgets import DateTimeInput
from .models import Booking
from blog.models import Car
from django.utils.safestring import mark_safe

class CarModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return mark_safe(f'<b>{obj.name}</b>')  # Customize label as needed

class BookingForm(forms.ModelForm):
    car = CarModelChoiceField(
        queryset=Car.objects.all(),
        empty_label=None
    )

    class Meta:
        model = Booking
        fields = ['name', 'surname', 'nationality', 'city', 'address', 'phone_number', 'patent_number', 'insurance', 'period_start', 'period_end']
        widgets = {
            'period_start': DateTimeInput(attrs={'type': 'date', 'format': '%Y-%m-%d'}),
            'period_end': DateTimeInput(attrs={'type': 'date', 'format': '%Y-%m-%d'}),
        }

    def __init__(self, *args, **kwargs):
        super(BookingForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True

bookings/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from datetime import timedelta
from .forms import BookingForm
from .models import Booking
from blog.models import Car
from django.urls import reverse
from django.utils import timezone
from django.utils.dateparse import parse_date
import requests
from .models import BusyDate
import json
from django.http import JsonResponse
from django.core.mail import send_mail
from django.conf import settings

def booking_form(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            car = form.cleaned_data['car'].id
            start_time = form.cleaned_data['period_start']
            end_time = form.cleaned_data['period_end']

            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            nationality = form.cleaned_data['nationality']
            city = form.cleaned_data['city']
            address = form.cleaned_data['address']
            phone_number = form.cleaned_data['phone_number']
            patent_number = form.cleaned_data['patent_number']
            insurance = form.cleaned_data['insurance']

            booking = form.save(commit=False)
            booking.save()

            # Store the unavailable date range
            BusyDate.objects.create(
                car_id=car,
                start_date=start_time,
                end_date=end_time
            )

            form_data_string = f"Car ID: {car}\nStart Time: {start_time}\nEnd Time: {end_time}\n\nName: {name}\nSurname: {surname}\nNationality: {nationality}\nCity: {city}\n Address: {address}\nPhone Number: {phone_number}\nPatent Number: {patent_number}\nInsurance: {insurance}"

            send_mail(
                'Booking Form',
                form_data_string,
                settings.EMAIL_HOST_USER,
                ['carrentalolympia@gmail.com'],
                fail_silently=False
            )

            messages.success(request, "Your booking has been successfully submitted.")
            return redirect(reverse('booking_confirmation'))
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"Error in {field}: {error}")
    else:
        # Set default values for period_start and period_end
        start_time = timezone.now().strftime('%Y-%m-%d')
        end_time = (timezone.now().date()  + timedelta(days=1)).strftime('%Y-%m-%d')
        initial_data = {'period_start': start_time, 'period_end': end_time}
        form = BookingForm(initial=initial_data)
        
        # Retrieve unavailable dates for selected car
        car_id = request.GET.get('car_id')  # Assuming the car_id is passed in the request
        if car_id:
            try:
                car = Car.objects.get(id=car_id)
                start_date = timezone.now().strftime('%Y-%m-%d')
                end_date = (timezone.now().date()  + timedelta(days=1)).strftime('%Y-%m-%d')
                response = requests.get(
                    reverse('get_unavailable_dates', args=[car_id]),
                    params={'start_date': start_date, 'end_date': end_date}
                )
                if response.status_code == 200:
                    unavailable_dates_str = response.text.split('\n')
                    unavailable_dates = [parse_date(date_str) for date_str in unavailable_dates_str]
                    form.fields['period_start'].unavailable_dates = unavailable_dates
                    form.fields['period_end'].unavailable_dates = unavailable_dates
                else:
                    messages.error(request, "Failed to retrieve unavailable dates.")
            except Car.DoesNotExist:
                messages.error(request, "Car not found.")
    return render(request, 'bookings/booking_form.html', {'form': form})

def booking_confirmation(request):
    try:
        latest_booking = Booking.objects.latest('id')
    except Booking.DoesNotExist:
        latest_booking = None
        messages.error(request, "No bookings found.")
        return redirect('booking_form')  # Redirect back to booking form if no bookings found
    return render(request, 'bookings/booking_confirmation.html', {'booking': latest_booking})

def get_unavailable_dates(request, car_id):
    try:
        busy_dates = BusyDate.objects.filter(car_id=car_id)
        busy_dates_json = [{'title': 'Busy', 'start': str(busy.start_date), 'end': str(busy.end_date)} for busy in busy_dates]
        return JsonResponse(busy_dates_json, safe=False)
    except BusyDate.DoesNotExist:
        return JsonResponse([], safe=False)

def render_calendar(request):
    busy_dates = BusyDate.objects.all()
    busy_dates_json = [{'title': 'Unavailable', 'start': str(busy.start_date), 'end': str(busy.end_date)} for busy in busy_dates]
    return JsonResponse(busy_dates_json, safe=False)

bookings/templates/bookings/booking_confirmation.html
<!-- booking_confirmation.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Add necessary meta tags, title, and CSS links -->
</head>
<body>
    <div class="container">
        <h2 class="text-center mb-4">Booking Confirmation</h2>
        <p>Your booking details:</p>
        <ul>
            <li>Name: {{ booking.name }}</li>
            <li>Surname: {{ booking.surname }}</li>
            <li>Nationality: {{ booking.nationality }}</li>
            <li>City: {{ booking.city }}</li>
            <li>Adress: {{ booking.address }}</li>
            <li>Phone Number: {{ booking.phone_number }}</li>
            <li>Patent Number: {{ booking.patent_number }}</li>
            <li>Insurance: {{ booking.insurance }}</li>
            <li>Period Start: {{ booking.period_start }}</li>
            <li>Period End: {{ booking.period_end }}</li>
            <!-- Add other booking details here -->
        </ul>
        <p>Send a Screenshot of this Page to the following number to confirm your order: +355 69 255 2794</p>
        
        <!-- Option to book another car -->
        <a href="{% url 'booking_form' %}" class="btn btn-primary"></a>
    </div>
</body>
</html>

bookings/templates/bookings/booking_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Form</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://unpkg.com/fullcalendar@5/main.min.css' rel='stylesheet' />
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            max-width: 500px;
            margin: 5% auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            margin-right: 20px;
            margin-left: 20px;
        }
        label {
            font-weight: bold;
        }
        button[type="submit"] {
            width: 100%;
        }
        #calendar {
            margin-top: 20px;
        }

        /* Updated CSS to hide the spinners, now including the standard appearance property */
    input[type="number"]::-webkit-inner-spin-button, 
    input[type="number"]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        appearance: none; /* Standard property for all browsers */
        margin: 0;
    }
    input[type="number"] {
        -moz-appearance: textfield; /* Firefox */
        appearance: textfield; /* Standard property for all browsers where it's applicable */
    }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="text-center mb-4">Booking Form</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_car">Car</label>
                {{ form.car }}
            </div>
            <!-- Additional form fields -->
            <div class="form-group">
                <label for="id_name">Name</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="id_surname">Surname</label>
                {{ form.surname }}
            </div>
            <div class="form-group">
                <label for="id_nationality">Nationality</label>
                {{ form.nationality }}
            </div>
            <div class="form-group">
                <label for="id_city">City</label>
                {{ form.city }}
            </div>
            <div class="form-group">
                <label for="id_address">Address</label>
                {{ form.address }}
            </div>
            <div class="form-group">
                <label for="id_phone_number">Phone Number</label>
                <input type="number" id="id_phone_number" name="phone_number" required>
            </div>
            <div class="form-group">
                <label for="id_patent_number">Patent Number</label>
                {{ form.patent_number }}
            </div>
            <div class="form-group">
                <label for="id_insurancer">Insurance</label>
                {{ form.insurance }}
            </div>
            <div class="form-group">
                <label for="id_period_start">Period Start</label>
                {{ form.period_start }}
            </div>
            <div class="form-group">
                <label for="id_period_end">Period End</label>
                {{ form.period_end }}
            </div>
            <!-- End additional form fields -->
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <div id='calendar'></div> <!-- Div for FullCalendar -->
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src='https://unpkg.com/fullcalendar@5/main.min.js'></script>
    <script>
        $(document).ready(function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                events: [], // Initially no events
                eventColor: 'blue' // Default color for available dates
            });
            calendar.render();
            var defaultCarId = $('#id_car').val();
        var startDate = $('#id_period_start').val();
        var endDate = $('#id_period_end').val();
            if (defaultCarId && startDate && endDate) {
            var formattedStartDate = formatDate(new Date(startDate));
            var formattedEndDate = formatDate(new Date(endDate));

            var url = `/bookings/unavailable-dates/${defaultCarId}/?start_date=${formattedStartDate}&end_date=${formattedEndDate}`;

            $.ajax({
                url: url,
                success: function(data) {
                    renderCalendar(data);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.error("AJAX error: " + textStatus + ' : ' + errorThrown);
                }
            });
        }
            $('#id_car').change(function() {
                var carId = $(this).val();
                var startDate = $('#id_period_start').val();
                var endDate = $('#id_period_end').val();
        
                if (carId && startDate && endDate) {
                    var formattedStartDate = formatDate(new Date(startDate));
                    var formattedEndDate = formatDate(new Date(endDate));
        
                    var url = `/bookings/unavailable-dates/${carId}/?start_date=${formattedStartDate}&end_date=${formattedEndDate}`;
        
                    $.ajax({
                        url: url,
                        success: function(data) {
                            renderCalendar(data);
                        },
                        error: function(jqXHR, textStatus, errorThrown) {
                            console.error("AJAX error: " + textStatus + ' : ' + errorThrown);
                        }
                    });
                } else {
                    calendar.removeAllEvents(); // Clear the calendar if no valid car or dates
                    calendar.render();
                }
            });
        
            // Function to render busy dates in the calendar
            function renderCalendar(busyDates) {
                calendar.removeAllEvents(); // Clears existing events before adding new ones
                
                busyDates.forEach(function(date) {
                    var startDate = new Date(date.start);
                    var endDate = new Date(date.end);

                    // Iterate over each day in the busy period
                    var currentDate = new Date(startDate); 
                    while (currentDate <= endDate) {
                        calendar.addEvent({
                            title: 'Busy',
                            start: currentDate,
                            color: 'red', // Specific color for busy dates
                            allDay: true
                        });

                        // Move to the next day
                        currentDate.setDate(currentDate.getDate() + 1);
                    }
                });

    calendar.render(); // Re-render the calendar to show new events
}

        
            function formatDate(date) {
                var year = date.getFullYear();
                var month = (date.getMonth() + 1).toString().padStart(2, '0');
                var day = date.getDate().toString().padStart(2, '0');
                return year + "-" + month + "-" + day;
            }
        });
        </script>

        
        
    
</body>
</html>